trigger:
  branches:
    include:
      - master
      - dev

pr:
  branches:
    include:
      - master
      - dev

variables:
  solution: 'NogasmChart.sln'
  buildPlatform: 'Any CPU'

jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        # Debug:
        #   buildConfiguration: Debug
        Release:
          buildConfiguration: Release
    steps:
      - template: build/build-start.yml
        parameters:
          platform: "win-x64"
      # Set up key after build start, otherwise we won't have nuget to update yet.
      - task: VSBuild@1
        displayName: "Build Project"
        inputs:
          solution: '$(solution)'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'
          maximumCpuCount: true
      - task: PowerShell@2
        displayName: "Build Installer"
        inputs:
          targetType: inline
          script: |
            $Env:CONFIGURATION = "$(buildConfiguration)"
            $Env:BUILD_VERSION = "$(gitVersion)"
            cinst -y --no-progress innosetup
            ISCC nogasm-chart-installer.iss
            move installer\nogasm-chart-installer.exe installer\$(cliBuildName)-installer.exe
      - task: CopyFiles@2
        displayName: "Copy installer to staging"
        inputs:
          contents: "$(System.DefaultWorkingDirectory)/installer/*.exe"
          targetFolder: '$(Build.ArtifactStagingDirectory)'
          flattenFolders: true
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'win-x64-$(buildConfiguration)'
